"""The campus's geometry, as the client's own map files state it.

``reference/mapgraph.json`` is generated by ``the map exporter export`` out of
every map's ``cld_*.bin`` — 78 maps, their cell grids, which of their 126555
cells can be stood on, and all 817 doorway destinations. See that tool's
docstring for the file format and for what the wire has and has not confirmed.

The server needs none of this to run: warping already works because the client
decides where a door leads and the server only agrees. What the graph buys is
the ability to *check* that agreement, and to name real cells on maps nobody has
walked yet — up to now the only coordinates known to be good were the ones the
player had already stood on.

Missing or unreadable, everything here degrades to "no opinion" rather than
refusing to serve: a warp the graph cannot vouch for is still answered Ok.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

GRAPH_PATH = Path(__file__).resolve().parent.parent / "reference" / "mapgraph.json"


def _load() -> dict[int, dict]:
    try:
        raw = json.loads(GRAPH_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"[maps] no map graph ({exc}); warps go unchecked")
        return {}
    graph = {int(key): value for key, value in raw.items()}
    for entry in graph.values():
        packed = entry.get("walk")
        entry["walk"] = base64.b64decode(packed) if packed else None
    return graph


GRAPH = _load()


def name(map_id: int) -> str:
    """The map's Japanese name, as map.txt spelled it when the graph was built."""
    entry = GRAPH.get(map_id)
    return entry["name"] if entry else str(map_id)


def size(map_id: int) -> tuple[int, int] | None:
    """``(width, height)`` in cells, or None for a map with no data."""
    entry = GRAPH.get(map_id)
    return tuple(entry["size"]) if entry else None  # type: ignore[return-value]


def inside(map_id: int, pos: tuple[int, int]) -> bool:
    """Whether a cell is on the map at all. Says nothing about walking there."""
    bounds = size(map_id)
    if bounds is None:
        return True
    return 0 <= pos[0] < bounds[0] and 0 <= pos[1] < bounds[1]


def walkable(map_id: int, pos: tuple[int, int]) -> bool | None:
    """Whether a cell has a floor under it, or None where the graph has no opinion.

    The client's own collision file says so: the ``u16`` at cell offset 0xa is
    0xffff exactly where there is nothing to stand on. Every cell the player has
    ever moved onto, every doorway cell, and every cell a doorway delivers into
    passes this, and on all 78 maps the walkable cells are one connected blob.

    It is not the whole story of what blocks a step. The file knows about
    architecture and not about props: 屋外's fixed decoration squares, where the
    seasonal 門松 and 案山子 stand, read as plain floor. So a False here is
    trustworthy and a True means "the ground exists", not "nothing is in the way".
    """
    entry = GRAPH.get(map_id)
    if entry is None or entry["walk"] is None or not inside(map_id, pos):
        return None
    width = entry["size"][0]
    index = pos[1] * width + pos[0]
    return bool(entry["walk"][index >> 3] & (1 << (index & 7)))


def nearest_walkable(
    map_id: int, pos: tuple[int, int], reach: int = 8
) -> tuple[int, int] | None:
    """The closest cell with a floor, ``pos`` itself if it already has one.

    Searched in rings so the answer is the nearest by Chebyshev distance, and
    capped at ``reach`` so a caller that asks about the middle of a building
    gets None rather than a cell on the far side of a wall. Callers that want
    "somewhere sensible to put a thing" want this; ``landing`` is the stronger
    claim, because there the client has already chosen the cell itself.
    """
    if walkable(map_id, pos) is None:
        return None
    for radius in range(reach + 1):
        best = None
        for dy in range(-radius, radius + 1):
            for dx in range(-radius, radius + 1):
                if max(abs(dx), abs(dy)) != radius:
                    continue
                cell = (pos[0] + dx, pos[1] + dy)
                if walkable(map_id, cell):
                    # Ties broken by true distance so a ring's corners lose to
                    # its edges; a marker nudged out of a wall should come back
                    # on the near side of it, not diagonally past the corner.
                    score = dx * dx + dy * dy
                    if best is None or score < best[0]:
                        best = (score, cell)
        if best is not None:
            return best[1]
    return None


def door_at(map_id: int, pos: tuple[int, int]) -> int | None:
    """The door id of the cell being stood on, if it is a doorway."""
    for door in GRAPH.get(map_id, {}).get("doors", []):
        if [pos[0], pos[1]] in door["cells"]:
            return door["door"]
    return None


def exits(map_id: int) -> list[tuple[int, int, tuple[int, int], tuple[int, int, int, int]]]:
    """``[(door id, index, cell, (mapId, posX, posY, dir))]`` for one map.

    Flattened over both fans-out: a door can occupy several cells and can offer
    several destinations, so one door id may appear more than once.
    """
    out = []
    for door in GRAPH.get(map_id, {}).get("doors", []):
        for index, dest in enumerate(door["to"]):
            for cell in door["cells"]:
                out.append((door["door"], index, (cell[0], cell[1]), tuple(dest)))
    return out


def arrivals(map_id: int) -> list[tuple[int, int, int]]:
    """``(posX, posY, dir)`` cells that some other map's doorway delivers into.

    The best-attested standable cells on a map nobody has walked. A door cell is
    standable because the player has to step on it, but an *arrival* cell is
    where the client itself chooses to put someone — it is the one coordinate in
    the whole file the client has already committed to as a landing spot.
    """
    seen: dict[tuple[int, int], int] = {}
    for other in GRAPH:
        for _, _, _, (dest_map, dest_x, dest_y, direction) in exits(other):
            if dest_map == map_id:
                seen.setdefault((dest_x, dest_y), direction)
    return [(x, y, d) for (x, y), d in sorted(seen.items())]


def landing(map_id: int) -> tuple[int, int] | None:
    """Somewhere to stand on a map, or None if the graph cannot vouch for one.

    Arrivals first; a map with none — 屋外 is one, nothing warps *to* it without
    naming a cell — falls back to its own doorway cells.

    Only the cell comes back. Every record here also carries a ``dir`` in
    ``{2,4,6,8}``, and it is *not* the protocol's ``direction`` — walking into
    the cafeteria has the table saying 8 while the client says 5. Handing the
    map file's value to a message expecting the other one was passing off a
    number from the wrong namespace as an answer; callers pick a direction they
    can actually vouch for.
    """
    for x, y, _ in arrivals(map_id):
        return x, y
    for _, _, cell, _ in exits(map_id):
        return cell[0], cell[1]
    return None


def search(query: str) -> list[tuple[int, str]]:
    """``(mapId, name)`` for a numeric id or a substring of a map's name."""
    if query.isdigit() and int(query) in GRAPH:
        return [(int(query), name(int(query)))]
    return sorted(
        (map_id, entry["name"])
        for map_id, entry in GRAPH.items()
        if query and query in entry["name"]
    )


def explain_warp(
    from_map: int, from_pos: tuple[int, int], to_map: int, to_pos: tuple[int, int]
) -> str:
    """One line saying whether a warp request matches a door in the graph.

    Purely diagnostic. A mismatch is far more likely to mean the server lost
    track of where the player was standing than that the client made something
    up, so this reports rather than rejects.
    """
    if not GRAPH:
        return "no map data, unchecked"
    door = door_at(from_map, from_pos)
    for door_id, _, cell, (dest_map, dest_x, dest_y, direction) in exits(from_map):
        if (dest_map, dest_x, dest_y) == (to_map, to_pos[0], to_pos[1]):
            standing = "standing on it" if cell == from_pos else f"door cell at {cell}"
            return f"matched door {door_id} ({standing}, table dir={direction})"
    if door is not None:
        return f"standing on door {door}, but the destination is not the one in the table"
    if not inside(to_map, to_pos):
        return f"destination {to_pos} is outside map {to_map}'s {size(to_map)}"
    if walkable(to_map, to_pos) is False:
        return f"destination {to_pos} has no floor on map {to_map}"
    return "no door in the table leads from here to there"
