"""The local stand-in for the website 登録 happened on.

A registration code in the box did not work on its own. The player went to
KONAMI's site, signed in with their KONAMI ID, typed the code from the box, and
only then would the login screen let them in -- and the client still carries the
sentences that step produced, one for a code nobody has claimed and one for a
code that needs claiming again. codes.py sets out how those sentences are the
evidence for the step.

Nothing of that page survives to copy, and nothing needs to: what is being
reproduced is the step, not KONAMI's markup. So this is a plain form on a plain
port, with the two things their site did and nothing else --

    make a KONAMI ID          an id and a personal key, which is what the
                              client's login screen asks for
    登録 a code               bind one code to one KONAMI ID, which is what
                              turns it from `issued` into `active`

-- and no third thing. There is no email step, because there is nobody to mail:
the address on KONAMI's form existed to prove a person could be reached, and a
server for the room it is running in has no use for that proof. See the README
on why this is not meant to face a network.

  One form, two steps
  -------------------
  Those two steps are one form for the player. KONAMI's sequence had a code
  arrive in a printed box before any of this began, and here there is no box: an
  id and a personal key are typed, and the code is generated and bound in the
  same request.

  Nothing about the model moves. The handler calls issue() and then register(),
  the same two calls in the same order, and a code still passes through `issued`
  on its way to `active` -- what is gone is the wait in between, which existed
  only because the code had been printed months earlier. The evidence for the
  two stages is in the client's own refusal table and is set out at the top of
  codes.py; it is about what the original could tell apart, not about how long a
  code sat between the stages.

  The stages stay separately reachable at /register, and not only for the tests.
  A code an operator generated by hand and handed to somebody has no other way
  in, and reason 24 (レジストレーションコードが登録されていません) has no other
  way to be produced.

  Signing up twice
  ----------------
  Asking for an account that already exists, with the personal key that opens
  it, shows the code that account already has rather than issuing a second one.
  That is one answer to three separate questions -- a reloaded success page, a
  player who lost the code, and somebody collecting codes -- and it is why
  nothing on this page is unrecoverable. It does mean the code can be retrieved
  by whoever knows the id and the key, which is a real cost and a small one:
  those two already open the account.

  The back button
  ---------------
  Nothing either form does is answered with a page. Every outcome is a 303 to a
  GET -- /done for a code, back to /signup or /register for anything else -- and
  what that GET should draw waits for TICKET_TTL under a token in memory.

  A page that *is* the answer to a POST cannot be returned to. This server sends
  no-store, so the browser has nothing to go back to and offers to send the form
  again instead, which arrives as a wall of text about resubmitting a form on
  the way back to a page the player had already been told to write down. Making
  the resubmission harmless was not enough, because the player never gets as far
  as finding out that it is.

  ⚠️ The refusals need this as much as the code does, which is not obvious and
  was got wrong once. A rejected form looks like a page nobody returns to --
  they are about to correct it and send it again -- but it stays in the history
  either way, and every later press of the back button has to walk over it. One
  mistyped id is enough to put it there.

  What is left is a pair of ordinary pages: back and reload both work, and /done
  is a link that can sit in a tab while twenty characters are copied out of it.
  It expires, and losing it is not losing the code -- the form gives the same one
  back to the same id and key, which is why this is safe to keep in memory and
  to throw away on restart.

  Language
  --------
  The page is written in English, and the field labels are in Japanese, and that
  split is deliberate rather than sloppy. A player is copying values between this
  page and the client's login screen, and that screen says KONAMI ID,
  パーソナルキー and レジストレーションコード; a label that does not match the
  box it corresponds to is a page that has to be decoded before it can be used.
  Everything the page says in its own voice is in English, as the rest of this
  tree is.

  ⚠️ 登録 is not one of those labels, and had been used as a verb on the page --
  "登録 a registration code", a button reading 登録 -- until it was noticed that
  it matches nothing the player can see. The login screen has three fields and
  no such button, and the step it names happened on a website whose markup does
  not survive. So the word stays in this file's prose and in its log lines,
  where it names a historical step for whoever is reading the code, and it is
  English wherever the page is speaking to a player. The one place a player is
  shown 登録 is inside 「レジストレーションコードが登録されていません」, which is
  quoted because it is what the client itself will say to them.
"""

from __future__ import annotations

import asyncio
from datetime import date
import html
import json
from pathlib import Path
import secrets
import time
from urllib.parse import parse_qs

import codes
import konami_id
from common import ServiceConfig

# Where the client's login screen splits the twenty characters. Reproduced here
# so that a code is typed the same way in both places -- and so that a player
# reading one off this page can follow it group by group.
GROUPS = codes.CODE_LEN // codes.GROUP_LEN

STYLE = """
:root { color-scheme: light dark; }
body { font: 16px/1.6 system-ui, "Hiragino Sans", "Yu Gothic", sans-serif;
       margin: 0 auto; max-width: 46rem; padding: 2rem 1.25rem 4rem; }
h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
h2 { font-size: 1.1rem; margin: 2.5rem 0 .5rem; }
p.lede { color: #767676; margin: 0 0 2rem; }
form { border: 1px solid #8884; border-radius: .5rem; padding: 1.25rem; }
label { display: block; margin: .9rem 0 .25rem; font-weight: 600; }
label .en { font-weight: 400; color: #767676; margin-left: .5rem; }
label > input { display: block; margin-top: .3rem; }
input { font: inherit; padding: .4rem .5rem; border: 1px solid #8886;
        border-radius: .25rem; background: transparent; color: inherit; }
input[type=text], input[type=password] { width: 18rem; max-width: 100%; }
.code input { width: 4.5rem; text-align: center; text-transform: uppercase;
              font-family: ui-monospace, monospace; letter-spacing: .1em; }
.code { display: flex; flex-wrap: wrap; gap: .4rem; align-items: center; }
button { font: inherit; margin-top: 1.25rem; padding: .45rem 1.1rem;
         border-radius: .25rem; border: 1px solid #8886; cursor: pointer; }
.note { color: #767676; font-size: .9rem; }
.msg { border-radius: .5rem; padding: .75rem 1rem; margin: 0 0 1.5rem; }
.ok { border: 1px solid #3a3; background: #3a31; }
.bad { border: 1px solid #c44; background: #c441; }
code { font-family: ui-monospace, monospace; }
.code input[readonly] { font-size: 1.25rem; width: 5.5rem; padding: .5rem .3rem; }
.warn { border: 1px solid #c93; background: #c931; border-radius: .5rem;
        padding: .75rem 1rem; }
"""

# Two ledes because there are two audiences, and the difference between them is
# the first thing either one needs to know: one has no code and is here to be
# given one, the other is holding a code somebody handed them.
LEDE_SIGNUP = """Local revival server. Make an account here, then sign in with
the client using what this page gives you."""

LEDE_REGISTER = """Local revival server. For a registration code somebody gave
you. If you do not have one, <a href="/">start here</a> instead."""


def page(
    body: str,
    message: tuple[str, str] | None = None,
    *,
    lede: str = LEDE_SIGNUP,
) -> bytes:
    banner = ""
    if message is not None:
        kind, text = message
        banner = f'<p class="msg {kind}">{text}</p>'
    # noindex because there is no version of this page that is improved by being
    # found in a search result. Somebody who should be here was told where it is;
    # robots.txt says the same thing to whatever reads that instead.
    return f"""<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Registration</title>
<style>{STYLE}</style>
<h1>Registration</h1>
<p class="lede">{lede}</p>
{banner}
{body}
""".encode("utf-8")


ROBOTS = b"User-agent: *\nDisallow: /\n"

# How long a /done link keeps working. Long enough to copy twenty characters and
# to come back to the tab after a distraction, short enough that the link stops
# being one before it is forgotten about in somebody's history.
TICKET_TTL = 15 * 60

EXPIRED_TICKET = (
    "That link has expired. Fill this in again with the same KONAMI ID and "
    "personal key and it will show you the same code."
)


def code_boxes(values: list[str]) -> str:
    boxes = []
    for i in range(GROUPS):
        value = html.escape(values[i]) if i < len(values) else ""
        if i:
            boxes.append("<span>-</span>")
        boxes.append(
            f'<input name="code{i}" maxlength="{codes.GROUP_LEN}" '
            f'value="{value}" autocapitalize="characters" spellcheck="false">'
        )
    return '<div class="code">' + "".join(boxes) + "</div>"


def code_shown(key: str) -> str:
    """A finished code, in the five boxes the login screen splits it into.

    Read-only inputs rather than text, for the same reason code_boxes exists:
    the player is transcribing this into five boxes that look like these, and a
    run of twenty characters is transcribed wrong.
    """
    boxes = []
    for i, group in enumerate(codes.format_code(key).split("-")):
        if i:
            boxes.append("<span>-</span>")
        boxes.append(
            f'<input value="{html.escape(group)}" readonly spellcheck="false">'
        )
    return '<div class="code">' + "".join(boxes) + "</div>"


def signup(form: dict[str, str] | None = None) -> str:
    """The whole of what a player without a code has to do."""
    form = form or {}
    got = lambda name: html.escape(form.get(name, ""))  # noqa: E731
    return f"""
<form method="post" action="/signup">
  <p class="note">These are the two things the client's login screen asks for at
  the top. The registration code goes underneath them, and this page will give
  you one.</p>
  <label>KONAMI ID <span class="en">up to 64 of A-Z a-z 0-9 . _ -</span>
    <input type="text" name="konami_id" value="{got('konami_id')}"
           autocapitalize="none" spellcheck="false"></label>
  <label>パーソナルキー <span class="en">personal key, at least
    {konami_id.KEY_MIN} characters</span>
    <input type="password" name="personal_key"></label>
  <label>パーソナルキー（確認） <span class="en">again</span>
    <input type="password" name="confirm"></label>
  <p class="note">⚠ This page is not encrypted, so pick something you do not use
  anywhere else. It only unlocks a character in this game.</p>
  <button type="submit">Create</button>
</form>
<p class="note">Given a registration code by somebody?
<a href="/register">Register it here</a> instead.</p>
"""


def ticket(owner: str, key: str) -> str:
    """The page a player takes away. Deliberately has no form on it.

    Redrawing the form under a code that was just handed out is an invitation to
    submit it again, and the second submission is the one that would have looked
    like a failure before signing up twice was made to answer with this same
    page.
    """
    return f"""
<h2>Your registration code</h2>
{code_shown(key)}
<p class="warn">⚠ Write this down. Nothing mails it to you. It is shown again
only by coming back to this page with the same KONAMI ID and personal key.</p>
<p>Sign in on the client with:</p>
<ul>
  <li>KONAMI ID <code>{html.escape(owner)}</code></li>
  <li>パーソナルキー — the one you just chose</li>
  <li>レジストレーションコード — the five groups above</li>
</ul>
"""


def forms(form: dict[str, str] | None = None) -> str:
    """Both forms, with whatever the player last typed still in them.

    Keeping the values is not a nicety: a rejected 登録 is usually a mistyped
    group out of five, and a page that clears all five makes the player retype
    the four that were right.
    """
    form = form or {}
    got = lambda name: html.escape(form.get(name, ""))  # noqa: E731
    typed = [form.get(f"code{i}", "") for i in range(GROUPS)]
    return f"""
<h2>1. Make a KONAMI ID</h2>
<form method="post" action="/konami-id">
  <p class="note">Only needed once. This is what the client's login screen asks
  for at the top; the registration code goes underneath it.</p>
  <label>KONAMI ID <span class="en">up to 64 of A-Z a-z 0-9 . _ -</span>
    <input type="text" name="konami_id" value="{got('konami_id')}"
           autocapitalize="none" spellcheck="false"></label>
  <label>パーソナルキー <span class="en">personal key, at least
    {konami_id.KEY_MIN} characters</span>
    <input type="password" name="personal_key"></label>
  <label>パーソナルキー（確認） <span class="en">again</span>
    <input type="password" name="confirm"></label>
  <button type="submit">Create</button>
</form>

<h2>2. Register a code you were given</h2>
<form method="post" action="/register">
  <p class="note">Binds one code to one KONAMI ID. Until this is done the login
  screen answers
  「レジストレーションコードが登録されていません」.</p>
  <label>KONAMI ID
    <input type="text" name="konami_id" value="{got('konami_id')}"
           autocapitalize="none" spellcheck="false"></label>
  <label>パーソナルキー
    <input type="password" name="personal_key"></label>
  <label>レジストレーションコード <span class="en">the five groups, as on the
    login screen</span></label>
  {code_boxes(typed)}
  <button type="submit">Register</button>
</form>
"""


# The client's own words for the refusals this page can run into, so that a
# player is told here exactly what the login screen would have told them. Taken
# from the client's MsgSvNgLoginServerLogin table; see codes.py for the reasons.
REASON_TEXT = {
    codes.REASON_UNKNOWN: "入力されたレジストレーションコードは存在しません。",
    codes.REASON_EXPIRED: "レジストレーションコードの有効期限が過ぎています。",
    codes.REASON_SUSPENDED: "アカウント停止期間中です。",
}


class RegistrationSite:
    """The 登録 form, on a port a browser can reach.

    Plain HTTP on purpose, and the reason is a certificate rather than
    indifference. The client's auth endpoints are TLS because the client insists
    on it, and that certificate is 1024-bit RSA signed with SHA-1 -- which every
    current browser refuses outright, so serving this page from the same context
    would make it unreachable by the only thing that can render it. A second,
    current certificate would have to be issued against a name, and this server
    is reached by address.

    So a personal key crosses this connection in the clear, and the page says so
    rather than leaving it to be found out. What that is worth depends on where
    the browser is: on the machine running the server it is nothing, and across
    a network it is a password in plaintext. konami_id.py sets out what a
    personal key is here -- a label with a lock drawn on it, weak because the
    client's login screen imposes the shape -- which is why this is a sentence
    on the form and not a refusal to serve the page, and why the sentence says
    to pick something not used anywhere else.
    """

    def __init__(
        self,
        root: Path,
        config: ServiceConfig,
        *,
        directory: konami_id.Directory,
        table: codes.CodeTable,
        advertise_ip: str = "127.0.0.1",
    ) -> None:
        self.root = root
        self.config = config
        self.directory = directory
        self.codes = table
        self.advertise_ip = advertise_ip
        # token -> (what the next GET should draw, when it stops working). In
        # memory and gone on restart, which is the right lifetime for something
        # whose loss costs a player one more trip through the form.
        self._handoffs: dict[str, tuple[dict, float]] = {}

    # -- what the POST leaves for the GET to draw ---------------------------

    def _keep(self, **payload) -> str:
        now = time.monotonic()
        for token, (_, expires) in list(self._handoffs.items()):
            if expires <= now:
                del self._handoffs[token]
        token = secrets.token_urlsafe(16)
        self._handoffs[token] = (payload, now + TICKET_TTL)
        return token

    def _read(self, token: str) -> dict | None:
        """What that token stands for, or None. Reading does not spend it.

        Spending it on the first read would put the reload it exists to allow
        straight back into the hands of the error it exists to avoid.
        """
        kept = self._handoffs.get(token)
        if kept is None:
            return None
        payload, expires = kept
        if expires <= time.monotonic():
            del self._handoffs[token]
            return None
        return payload

    def _see_other(self, path: str, **payload) -> bytes:
        token = self._keep(**payload)
        return self._respond(
            b"", b"303 See Other", location=f"{path}?t={token}".encode("ascii")
        )

    # -- the number worth keeping -----------------------------------------

    def _note_signup(self) -> int:
        """Add one to today's count and return it. Counts, and nothing else.

        A number per day is enough to notice that something has changed, which
        is the only thing this is for. Addresses are deliberately not written
        down: they would answer no question this asks, and a list of who played
        is a thing to have to look after rather than a thing to have.
        """
        path = self.codes.dir / "registrations.json"
        try:
            counts = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(counts, dict):
                counts = {}
        except (OSError, ValueError):
            counts = {}
        today = date.today().isoformat()
        counts[today] = int(counts.get(today, 0)) + 1
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                json.dumps(counts, indent=2, sort_keys=True), encoding="utf-8"
            )
        except OSError as exc:
            # Worth a line, not worth failing a registration that already
            # happened: the account and the code are both already on disk.
            print(f"[register] ⚠ could not record the count: {exc}")
        return counts[today]

    # -- the self-serve path ------------------------------------------------

    def _signup(
        self, form: dict[str, str]
    ) -> tuple[tuple[str, str], tuple[str, str] | None]:
        """Make an account and hand it a code.

        Returns (message, None) or (message, (konami id, code)). The pair comes
        back separately from the message because a success here replaces the
        page rather than annotating it, and because what goes on that page is
        the stored form of the id rather than what was typed into the box.
        """
        given = form.get("konami_id", "")
        key = form.get("personal_key", "")
        if key != form.get("confirm", ""):
            return ("bad", "The two personal keys do not match."), None
        try:
            wanted = konami_id.check_id(given)
            konami_id.check_personal_key(key)
        except konami_id.InvalidId as exc:
            return ("bad", html.escape(str(exc))), None

        if self.directory.exists(wanted):
            if not self.directory.verify(wanted, key):
                # This does say the id is taken, and it is the one place on
                # this page where being unhelpful was considered and rejected:
                # somebody has to pick a different id, and cannot be told to
                # without being told why. Nothing is given away by it either --
                # the form at /register has always answered the same question
                # the same way, out of create().
                return ("bad", (
                    "ユーザ情報が正しくありません。 That KONAMI ID is taken, "
                    "and that is not its personal key. Try another id."
                )), None
            mine = self.codes.codes_of(wanted)
            if mine:
                return ("ok", (
                    f"<code>{html.escape(wanted)}</code> already has a code. "
                    "Here it is again -- nothing new was issued."
                )), (wanted, mine[0])
            # Known id, no code: the account half of an earlier attempt that
            # did not get to the code half, or one made at /konami-id. Fall
            # through and give it one.
        else:
            try:
                self.directory.create(wanted, key)
            except konami_id.InvalidId as exc:  # lost a race for the name
                return ("bad", html.escape(str(exc))), None

        # issue() then register(), which is the original's two stages run
        # end to end. Not issue(state=STATE_ACTIVE): that one belongs to the
        # operator handing a code straight to somebody, and it is register()
        # that writes the owner.
        code = self.codes.issue(state=codes.STATE_ISSUED, note="self-serve")
        reason = self.codes.register(code, wanted)
        if reason is not None:
            # Cannot happen against a code issued one line ago, so if it does
            # the table is not what this thinks it is. Put the code back and say
            # nothing specific -- there is nothing here the player can act on.
            print(f"[register] ⚠ self-serve register({code}) refused with {reason}")
            self.codes.unregister(code)
            return ("bad", "Something went wrong issuing a code. Try again."), None
        today = self._note_signup()
        print(
            f"[register] self-serve {codes.format_code(code)} -> {wanted} "
            f"({today} today)"
        )
        return ("ok", f"Account <code>{html.escape(wanted)}</code> created."), (wanted, code)

    # -- the two things the page does -------------------------------------

    def _create_id(self, form: dict[str, str]) -> tuple[str, str]:
        given = form.get("konami_id", "")
        key = form.get("personal_key", "")
        if key != form.get("confirm", ""):
            return "bad", "The two personal keys do not match."
        try:
            made = self.directory.create(given, key)
        except konami_id.InvalidId as exc:
            return "bad", html.escape(str(exc))
        print(f"[register] new KONAMI ID {made}")
        return "ok", (
            f"KONAMI ID <code>{html.escape(made)}</code> created. "
            "Now register a code below."
        )

    def _register(self, form: dict[str, str]) -> tuple[str, str]:
        given = form.get("konami_id", "")
        typed = "".join(form.get(f"code{i}", "") for i in range(GROUPS))
        key = codes.normalise(typed)
        if not self.directory.verify(given, form.get("personal_key", "")):
            # One sentence for a wrong id and for a wrong key, which is the one
            # place on this page where being unhelpful is the point.
            return "bad", "ユーザ情報が正しくありません。 That KONAMI ID and personal key do not match."
        if not codes.is_wellformed(key):
            return "bad", (
                f"A registration code is {codes.CODE_LEN} characters in "
                f"{GROUPS} groups, and only uses "
                f"<code>{codes.ALPHABET}</code>."
            )
        owner = konami_id.normalise_id(given)
        already = self.codes.owner(key)
        if already == owner:
            return "ok", (
                f"<code>{codes.format_code(key)}</code> is already registered to "
                f"<code>{html.escape(owner)}</code>. Nothing to do."
            )
        reason = self.codes.register(key, owner)
        if reason is not None:
            return "bad", html.escape(REASON_TEXT.get(reason, f"reason {reason}"))
        print(f"[register] {codes.format_code(key)} registered to {owner}")
        return "ok", (
            f"<code>{codes.format_code(key)}</code> is registered to "
            f"<code>{html.escape(owner)}</code>. Sign in on the client with that "
            "KONAMI ID, that personal key, and this code."
        )

    # -- http -------------------------------------------------------------

    def _respond(
        self,
        body: bytes,
        status: bytes = b"200 OK",
        content_type: bytes = b"text/html; charset=utf-8",
        location: bytes | None = None,
    ) -> bytes:
        head = (
            b"HTTP/1.1 " + status + b"\r\n"
            b"Server: TokimekiOL-Local-Registration\r\n"
            b"Content-Type: " + content_type + b"\r\n"
            b"Cache-Control: no-store\r\n"
        )
        if location is not None:
            head += b"Location: " + location + b"\r\n"
        return (
            head + b"Connection: close\r\n"
            b"Content-Length: " + str(len(body)).encode("ascii") + b"\r\n\r\n" + body
        )

    def _handle_request(
        self,
        method: str,
        path: str,
        form: dict[str, str],
        query: dict[str, str] | None = None,
    ) -> bytes:
        query = query or {}
        if method != "POST":
            # Every path is spelled out. An earlier version answered anything
            # that was not a POST with the form, which made /robots.txt a page
            # of HTML -- the one file whose whole job is to not be that.
            if path == "/robots.txt":
                return self._respond(ROBOTS, content_type=b"text/plain; charset=utf-8")
            if path == "/done":
                shown = self._read(query.get("t", ""))
                if shown is None:
                    return self._respond(page(signup(), ("bad", EXPIRED_TICKET)))
                return self._respond(
                    page(ticket(shown["owner"], shown["code"]), shown["banner"])
                )
            if path in ("/", "/signup"):
                # An expired handoff draws the empty form and says nothing. The
                # values behind it are half a minute of typing, and there is no
                # message about them that is more use than the form itself.
                again = self._read(query.get("t", "")) or {}
                return self._respond(
                    page(signup(again.get("keep")), again.get("banner"))
                )
            if path in ("/register", "/konami-id"):
                again = self._read(query.get("t", "")) or {}
                return self._respond(
                    page(
                        forms(again.get("keep")),
                        again.get("banner"),
                        lede=LEDE_REGISTER,
                    )
                )
            return self._respond(page(signup()), b"404 Not Found")

        # The personal key is never echoed back into the page; every other field
        # is, so a rejected form can be corrected rather than retyped.
        keep = {k: v for k, v in form.items() if "key" not in k and k != "confirm"}

        if path == "/signup":
            message, made = self._signup(form)
            if made is None:
                return self._see_other("/signup", keep=keep, banner=message)
            owner, code = made
            return self._see_other("/done", owner=owner, code=code, banner=message)

        # The two-stage path. What it decides is untouched -- these are the same
        # two calls, and reason 24 is reachable through them exactly as before --
        # but it hands the answer over the same way the self-serve path does. A
        # page that cannot be gone back to is not better here for being the
        # older of the two.
        if path == "/konami-id":
            message = self._create_id(form)
        elif path == "/register":
            message = self._register(form)
        else:
            return self._respond(page(signup()), b"404 Not Found")
        return self._see_other("/register", keep=keep, banner=message)

    async def handle(
        self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter
    ) -> None:
        try:
            head = await asyncio.wait_for(reader.readuntil(b"\r\n\r\n"), timeout=30.0)
        except (asyncio.TimeoutError, asyncio.IncompleteReadError, ValueError):
            writer.close()
            return
        try:
            lines = head.decode("latin1").split("\r\n")
            method, target, *_ = lines[0].split(" ")
            path, _, raw_query = target.partition("?")
            query = {k: v[0] for k, v in parse_qs(raw_query).items()}
            length = 0
            for line in lines[1:]:
                name, _, value = line.partition(":")
                if name.strip().lower() == "content-length":
                    length = int(value.strip() or 0)
            # Bounded because this reads whatever the peer says is coming, and
            # the largest honest form here is a few hundred bytes.
            body = await reader.readexactly(min(length, 8192)) if length else b""
            form = {
                k: v[0]
                for k, v in parse_qs(body.decode("utf-8", "replace")).items()
            }
            response = self._handle_request(method, path, form, query)
        except Exception as exc:  # a malformed request is not a reason to die
            print(f"[register] bad request: {type(exc).__name__}: {exc}")
            response = self._respond(page(signup()), b"400 Bad Request")
        writer.write(response)
        try:
            await writer.drain()
        except Exception:
            pass
        writer.close()

    async def run(self) -> asyncio.AbstractServer:
        server = await asyncio.start_server(
            self.handle, self.config.host, self.config.port
        )
        print(
            f"[register] 登録 form on http://{self.advertise_ip}:{self.config.port}/"
        )
        return server
